### ISSUE TITLE
Union Bug

### ISSUE THREAD

**Issue by photopea** [r-flash/PathBool.js#2]
I can not compute the union of these three paths, the library throws an error:

    m658.03348 118.4966c7.85928 4.83645 114.84582 7.8304 127.89652 6.52531 20.97932-2.09799 43.06722-24.79623 43.06722-24.79623 0 0-96.43723-26.02101-108.97311-28.54836-20.22849-4.07832-78.95651 36.37872-61.99063 46.81928z
    m658.03348 115.88649c40.45718-30.01653 82.213-45.24662 103.10032-31.32163 7.83037 5.2203-3.58567 22.51547 13.05064 39.152 3.91519 3.9152-129.49099 2.06705-116.15096-7.83037z
    m680.87214 56.0165c2.20775-9.60391 62.6449-29.65403 101.79518-30.01652 17.61846-0.16312 119.39605 40.30737 130.50668 54.8128 5.8045 7.57806-76.88558 29.08762-91.35464 31.32162-15.28899 2.36056-144.20983-41.92525-140.94722-56.1179z

**Comment by r-flash** [comment]
Thanks for reporting! I'll look into it ASAP.

**Comment by r-flash** [comment]
I can reproduce the bug now. Will debug over the weekend.

**Comment by r-flash** [comment]
Sorry for the long wait, I was out for most of the weekends. This should be fixed now in current `master`. Can you please verify?

**Comment by photopea** [comment]
What is the "master"? Where can I find it? I am looking for a Javascript file that I can use inside my website.

**Comment by r-flash** [comment]
Sorry, I meant the master branch of this repository. The javascript files are inside the dist directory here: https://github.com/r-flash/PathBool.js/tree/master/dist. Which file is right for your needs depends on how you are including it into your website.

**Comment by photopea** [comment]
Okay, the new version can process the case from this issue, thanks a lot! It is running again in www.photopea.com, I will see if I get any other bug reports :)

**Comment by r-flash** [comment]
Awesome, thanks!
